Traceback (most recent call last):
  File "mbl.py", line 192, in <module>
    binance_msg = binance.buyAndRepay(config.Binance.ticker, binance.getMarginBalance(config.Binance.ticker))
  File "mbl.py", line 94, in buyAndRepay
    repay_msg = self.repay(ticker, amount)
  File "mbl.py", line 77, in repay
    return asset + "repaying fail. Error code : " + str(e.status_code) + " " + e.message
TypeError: can only concatenate str (not "int") to str
UnderMinTotalBid
Traceback (most recent call last):
  File "mbl.py", line 175, in <module>
    premium = getPremium()
  File "mbl.py", line 158, in getPremium
    btc_krw = upbit.getPrice('KRW-BTC')
  File "mbl.py", line 19, in getPrice
    return pyupbit.get_current_price(ticker)
  File "/home2/sewoong/.local/lib/python3.8/site-packages/pyupbit/quotation_api.py", line 248, in get_current_price
    data, req_limit_info = _call_public_api(url, markets=ticker)
  File "/home2/sewoong/.local/lib/python3.8/site-packages/pyupbit/request_api.py", line 64, in _call_public_api
    resp = _call_get(url, params=params)
  File "/home2/sewoong/.local/lib/python3.8/site-packages/pyupbit/errors.py", line 165, in wrapper
    resp = func(*args, **kwargs)
  File "/home2/sewoong/.local/lib/python3.8/site-packages/pyupbit/request_api.py", line 42, in _call_get
    return requests.get(url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1914, in do_handshake
    result = _lib.SSL_do_handshake(self._ssl)
KeyboardInterrupt
UnderMinTotalBid
Traceback (most recent call last):
  File "mbl.py", line 202, in <module>
    time.sleep(1)
KeyboardInterrupt
Traceback (most recent call last):
  File "mbl.py", line 197, in <module>
    bot.send("Premium 6% reached. " + config.waiting + " sec timmer start!")
TypeError: can only concatenate str (not "int") to str
UnderMinTotalBid
Traceback (most recent call last):
  File "mbl.py", line 188, in <module>
    bot.send("Buy Complete. " + upbit_msg + binance_msg)
  File "mbl.py", line 25, in getBalance
    return self.upbit.get_balance(ticker)
  File "/home2/sewoong/.local/lib/python3.8/site-packages/pyupbit/exchange_api.py", line 124, in get_balance
    balances, req = self.get_balances(contain_req=True)
  File "/home2/sewoong/.local/lib/python3.8/site-packages/pyupbit/exchange_api.py", line 101, in get_balances
    result = _send_get_request(url, headers=headers)
  File "/home2/sewoong/.local/lib/python3.8/site-packages/pyupbit/request_api.py", line 107, in _send_get_request
    resp = _call_get(url, headers=headers, data=data)
  File "/home2/sewoong/.local/lib/python3.8/site-packages/pyupbit/errors.py", line 165, in wrapper
    resp = func(*args, **kwargs)
  File "/home2/sewoong/.local/lib/python3.8/site-packages/pyupbit/request_api.py", line 42, in _call_get
    return requests.get(url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1821, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
KeyboardInterrupt
Traceback (most recent call last):
  File "mbl.py", line 206, in <module>
    
KeyboardInterrupt
Traceback (most recent call last):
  File "mbl.py", line 177, in <module>
    premium = getPremium()
  File "mbl.py", line 160, in getPremium
    btc_usdt = binance.getPrice("BTCUSDT")
  File "mbl.py", line 54, in getPrice
    return float(round(symbol['price'], 2))
TypeError: type str doesn't define __round__ method
Traceback (most recent call last):
  File "mbl.py", line 177, in <module>
    premium = getPremium()
  File "mbl.py", line 163, in getPremium
    tar_er = krw_price/usdt_price
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "mbl.py", line 205, in <module>
    upbit.getPrice()
TypeError: getPrice() missing 1 required positional argument: 'ticker'
UpbitError
Traceback (most recent call last):
  File "mbl.py", line 191, in <module>
    elif premium > 1.06 and upbit.getBalance(config.Upbit.ticker) > config.amount*0.8 :
  File "mbl.py", line 25, in getBalance
    return round(self.upbit.get_balance(ticker), 2)
TypeError: type NoneType doesn't define __round__ method
Traceback (most recent call last):
  File "mbl.py", line 206, in <module>
    time.sleep(1)
KeyboardInterrupt
Traceback (most recent call last):
  File "mbl.py", line 206, in <module>
    self.premium = premium
KeyboardInterrupt
Traceback (most recent call last):
  File "mbl.py", line 266, in <module>
    if timmer.getState() == False:
KeyboardInterrupt
InsufficientFundsBid
UpbitError
Traceback (most recent call last):
  File "mbl.py", line 252, in <module>
    if premium < buy_point and upbit.getBalance(config.Upbit.ticker) < config.amount*0.8:
  File "mbl.py", line 25, in getBalance
    return round(float(self.upbit.get_balance(ticker)), 2)
TypeError: float() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "mbl.py", line 281, in <module>
    time.sleep(1)
KeyboardInterrupt
Traceback (most recent call last):
  File "mbl.py", line 281, in <module>
    time.sleep(1)
KeyboardInterrupt
InsufficientFundsBid
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f9187dd38b0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ticker/price?symbol=BTCUSDT (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9187dd38b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mbl.py", line 250, in <module>
    premium = getPremium()
  File "mbl.py", line 233, in getPremium
    btc_usdt = binance.getPrice("BTCUSDT")
  File "mbl.py", line 53, in getPrice
    symbol = self.binance.get_symbol_ticker(symbol=ticker)
  File "/home2/sewoong/.local/lib/python3.8/site-packages/binance/client.py", line 1230, in get_symbol_ticker
    return self._get('ticker/price', data=params, version=self.PRIVATE_API_VERSION)
  File "/home2/sewoong/.local/lib/python3.8/site-packages/binance/client.py", line 371, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/home2/sewoong/.local/lib/python3.8/site-packages/binance/client.py", line 334, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home2/sewoong/.local/lib/python3.8/site-packages/binance/client.py", line 314, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ticker/price?symbol=BTCUSDT (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9187dd38b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "mbl.py", line 281, in <module>
    bot.send("Sell timming at " + str(premium))
KeyboardInterrupt
Traceback (most recent call last):
  File "mbl.py", line 352, in <module>
    time.sleep(1)
KeyboardInterrupt
Traceback (most recent call last):
  File "mbl.py", line 352, in <module>
    time.sleep(1)
KeyboardInterrupt
Traceback (most recent call last):
  File "mbl.py", line 352, in <module>
    time.sleep(1)
KeyboardInterrupt
